### PR TITLE
Blui 4793 fix builds

### PR DESCRIPTION
**Pull request by JeffGreiner-eaton**
Fixes BLUI-4793. Fix progress icon dev branch's failed build

#### Changes proposed in this Pull Request:

- Upgrade CI config to use latest cimg
- Upgrade react-scripts
- Update eslint and packages
- Update react demo app test
- Update react-native demo and added to test all in CI

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

- yarn && yarn start:angular
- or yarn && yarn start:react
- react native requires upgrading demos for iOS and Android

#### Any specific feedback you are looking for?

- logged issue for upgrading react & react-native. https://github.com/etn-ccis/blui-progress-icons/issues/157

### CODE REVIEW

**Review by huayunh — COMMENTED** [review]
## 1
Is this meant to be "part 1" of BLUI-4793? Because the story description says 

> circle CI should actually check the React demo project (and React Native too?). Currently, the package.json gives "test:demo-react": "echo 'No React Demo Test Script Yet'"

## 2
I did a fresh clone and ran `yarn && yarn start:react`. Here's what the console spit out. It still gives me a correct-looking webpage though.

> Failed to compile.
[eslint] Plugin "react" was conflicted between ".eslintrc.js » @brightlayer-ui/eslint-config/tsx » plugin:react/recommended" and "BaseConfig » /Users/c3050144/Documents/repos/blui-progress-icons/react/demo/node_modules/eslint-config-react-app/base.js".
ERROR in [eslint] Plugin "react" was conflicted between ".eslintrc.js » @brightlayer-ui/eslint-config/tsx » plugin:react/recommended" and "BaseConfig » /Users/c3050144/Documents/repos/blui-progress-icons/react/demo/node_modules/eslint-config-react-app/base.js".
webpack compiled with 1 error
No issues found.

But when I killed the terminal and re-run `yarn && yarn start:react`, this error message no longer shows.

**Comment by JeffGreiner-eaton** [comment]
> ## 1
> Is this meant to be "part 1" of BLUI-4793? Because the story description says
> 
> > circle CI should actually check the React demo project (and React Native too?). Currently, the package.json gives "test:demo-react": "echo 'No React Demo Test Script Yet'"
>  Yes this has been set to echo No React Demo Test Script Yet because there are no tests. Really there are no tests other than render the App in here.
> ## 2
> I did a fresh clone and ran `yarn && yarn start:react`. Here's what the console spit out. It still gives me a correct-looking webpage though.
> 
> > Failed to compile.
> > [eslint] Plugin "react" was conflicted between ".eslintrc.js » @brightlayer-ui/eslint-config/tsx » plugin:react/recommended" and "BaseConfig » /Users/c3050144/Documents/repos/blui-progress-icons/react/demo/node_modules/eslint-config-react-app/base.js".
> > ERROR in [eslint] Plugin "react" was conflicted between ".eslintrc.js » @brightlayer-ui/eslint-config/tsx » plugin:react/recommended" and "BaseConfig » /Users/c3050144/Documents/repos/blui-progress-icons/react/demo/node_modules/eslint-config-react-app/base.js".
> > webpack compiled with 1 error
> > No issues found.
> 
> But when I killed the terminal and re-run `yarn && yarn start:react`, this error message no longer shows.



> ## 1
> Is this meant to be "part 1" of BLUI-4793? Because the story description says
> 
> > circle CI should actually check the React demo project (and React Native too?). Currently, the package.json gives "test:demo-react": "echo 'No React Demo Test Script Yet'"
>  Yes this has been set to echo No React Demo Test Script Yet because there are no tests. Really there are no tests other than render the App in here for angular & react-native
> ## 2
> I did a fresh clone and ran `yarn && yarn start:react`. Here's what the console spit out. It still gives me a correct-looking webpage though.
> 
> > Failed to compile.
> > [eslint] Plugin "react" was conflicted between ".eslintrc.js » @brightlayer-ui/eslint-config/tsx » plugin:react/recommended" and "BaseConfig » /Users/c3050144/Documents/repos/blui-progress-icons/react/demo/node_modules/eslint-config-react-app/base.js".
> > ERROR in [eslint] Plugin "react" was conflicted between ".eslintrc.js » @brightlayer-ui/eslint-config/tsx » plugin:react/recommended" and "BaseConfig » /Users/c3050144/Documents/repos/blui-progress-icons/react/demo/node_modules/eslint-config-react-app/base.js".
> > webpack compiled with 1 error
> > No issues found.
> 
> But when I killed the terminal and re-run `yarn && yarn start:react`, this error message no longer shows.
This has been updated, can you try again.

**Comment by huayunh** [comment]
> Yes this has been set to echo No React Demo Test Script Yet because there are no tests. 
Really there are no tests other than render the App in here for angular & react-native

I think there should be at least a test to confirm that the demo app can be rendered smoothly. I will be looking for a part 2 of the story where the building demo app is added to the Circle CI steps.

**Review by huayunh — APPROVED** [review]
React app built smoothly. Will be for a "building react demo app" step in another PR.

**Comment by JeffGreiner-eaton** [comment]
> React app built smoothly. Will be for a "building react demo app" step in another PR.

ok here you go....

image

made adjustments, this is an outdated repo that needs updating. But for now it's good to go

**Review by huayunh — APPROVED** [review]

**Pull request merged**
